name: Deploy Pages

on:
  push:
    branches:
      - main
    paths:
      - 'example/**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build example for Web
        run: cd example && npx expo export --platform web
        env:
          EXPO_BASE_URL: /react-native-circle-layout

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: example/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
