name: EAS Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: Platform to build
        type: choice
        options:
          - all
          - ios
          - android
        default: all
      profile:
        description: EAS build profile
        type: choice
        options:
          - development
          - preview
          - production
        default: preview

concurrency:
  group: eas-build-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build on EAS
        working-directory: example
        run: eas build --platform ${{ inputs.platform }} --profile ${{ inputs.profile }} --non-interactive --no-wait
