name: Release
on:
  push:
    branches:
      - main

jobs:
  check-if-library-updated:
    if: github.event.repository.fork == false
    name: Check if there is an update to the library
    runs-on: ubuntu-latest
    outputs:
      IS_UPDATED: ${{ steps.is-library-updated.outputs.IS_UPDATED }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Check if there is a change in src
        id: is-library-updated
        run: |
          CHANGED_FILES=$(git diff --name-only $(git describe --tags --abbrev=0) HEAD -- 'src/')
          if [ -z "$CHANGED_FILES" ]; then
            echo "There are no changes in src directory"
            echo "IS_UPDATED=false" >> $GITHUB_OUTPUT
          else
            echo "There are changes in src directory"
            echo "IS_UPDATED=true" >> $GITHUB_OUTPUT
          fi

  release:
    needs: check-if-library-updated
    if: needs.check-if-library-updated.outputs.IS_UPDATED == 'true'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: yarn ci:install

      - name: Setup Git user
        run: |
          git config --global user.email "sonali.parekh912@gmail.com"
          git config --global user.name "Sonali Parekh"

      # Find the version to be released and store it in github env
      - name: Get release version
        id: release-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "VERSION=$(yarn release --release-version --npm.skipChecks | egrep -o '^([0-9]{1,}\.){2}[0-9]{1,}$')" >> $GITHUB_OUTPUT

      - name: Print release version
        run: echo "The next release version is ${{ steps.release-version.outputs.VERSION }}"

      # Create a release branch with the naming as - release-v{version}
      # push the branch to origin
      - name: Create branch for release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b release-v${{ steps.release-version.outputs.VERSION }}
          git remote set-url --push origin https://sonalip9:${{ secrets.GITHUB_TOKEN }}@github.com/sonalip9/react-native-circle-layout.git
          git push -u origin release-v${{ steps.release-version.outputs.VERSION }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn release --npm.skipChecks

      # raise a pr for this branch
      - name: Create pull request
        run: gh pr create -B main -H release-v${{ steps.release-version.outputs.VERSION }} --title 'Release v${{ steps.release-version.outputs.VERSION }}' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
