name: Release
on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*.*.*'
    paths:
      - 'src/**'
      - 'package.json'
      - '.github/workflows/npm-publish.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    if: "github.event.repository.fork == false && !startsWith(github.event.head_commit.message, 'chore: release')"
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup
        uses: ./.github/actions/setup

      - name: Get release version
        id: release-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "VERSION=$(pnpm release --release-version --npm.skipChecks | egrep -o '^([0-9]{1,}\.){2}[0-9]{1,}$')" >> $GITHUB_OUTPUT

      - name: Print release version
        run: echo "The next release version is ${{ steps.release-version.outputs.VERSION }}"

      - name: Setup Git user
        run: |
          git config --global user.email "sonali.parekh912@gmail.com"
          git config --global user.name "Sonali Parekh"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm release --npm.skipChecks --npm.publishArgs="--provenance"
