name: Test
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches:
  #     - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-push:
    if: github.event.repository.fork == false
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Git user
        run: |
          git config --global user.email "sonali.parekh912@gmail.com"
          git config --global user.name "Sonali Parekh"

      # Create a release branch with the naming as - release-v{version}
      # push the branch to origin
      - name: Create branch for release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b test-branch
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url --push origin https://sonalip9:${{github_token}}@github.com/sonalip9/react-native-circle-layout.git
          git push -u origin test-branch

      # raise a pr for this branch
      - name: Create pull request
        run: gh pr create -B main -H test-branch --title 'Merge test-branch into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
