name: Static Code Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  static-code-analysis:
    name: Run linter and TypeScript check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn ci:install
          yarn example install --frozen-lockfile  --prefer-offline

      - name: Run linter
        run: yarn lint

      - name: Run TypeScript check on the code
        run: yarn typescript

      - name: Run tests
        run: yarn test
